version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/pipeline-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/pipeline-python/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/serving-go/"
    schedule:
      interval: "weekly"
