services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server /data --console-address ":9001"
    networks:
      jackfruit:
    ports:
      - "9099:9000"
      - "9098:9001"

  ingestion:
    profiles: ["ingestion"]
    build:
      context: ./ingestion-go
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_healthy
    environment:
      ADS_BASE_URL: ${ADS_BASE_URL}
      ADS_API_KEY: ${ADS_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_RAW_BUCKET: ${MINIO_RAW_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      LOG_LEVEL: debug
    networks:
      jackfruit:

  dagster:
    build:
      context: ./pipeline-python
      dockerfile: Dockerfile
    environment:
      # Dagster env
      ENV: ${ENV}
      DOCKER_HOST: unix:///var/run/docker.sock
      # Forwarded to ingestion sibling container
      ADS_BASE_URL: ${ADS_BASE_URL}
      ADS_API_KEY: ${ADS_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_RAW_BUCKET: ${MINIO_RAW_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pipeline-python:/app
    ports:
      - "3099:3000"
    networks:
      jackfruit:

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./pipeline-python/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      jackfruit:

networks:
    jackfruit:
volumes:
  minio_data:
  postgres_data:
